spring:
  batch:
    job:
#      names: CsvImportJdbcJob
      names: CsvImportSkipJob
    jdbc:
      initialize-schema: never
#      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch2
    username: spring
    password: password

logging:
  level:
    '[com.example.demo]': debug
    